# Probably bad, will change
# todo todo
MACOS_PROBABLY_KNOWN_SYSTEM_DAEMONS = frozenset({
r"""/sbin/launchd""",
r"""/usr/libexec/logd""",
r"""/usr/libexec/smd""",
r"""/usr/libexec/UserEventAgent (System)""",
r"""/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/Support/fseventsd""",
r"""/System/Library/PrivateFrameworks/MediaRemote.framework/Support/mediaremoted""",
r"""/usr/sbin/systemstats --daemon""",
r"""/System/Library/PrivateFrameworks/MobileAccessoryUpdater.framework/Support/accessoryupdaterd 120""",
r"""/usr/libexec/configd""",
r"""endpointsecurityd""",
r"""/System/Library/CoreServices/powerd.bundle/powerd""",
r"""/usr/libexec/IOMFB_bics_daemon""",
r"""/usr/libexec/amfid""",
r"""/usr/libexec/keybagd -t 15""",
r"""/System/Library/PrivateFrameworks/MobileSoftwareUpdate.framework/Support/softwareupdated""",
r"""/System/Library/PrivateFrameworks/CoreSpeech.framework/corespeechd_system""",
r"""/usr/libexec/watchdogd""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Support/mds""",
r"""/System/Library/CoreServices/iconservicesd""",
r"""/usr/libexec/kernelmanagerd""",
r"""/usr/libexec/diskarbitrationd""",
r"""/usr/libexec/coreduetd""",
r"""/usr/sbin/syslogd""",
r"""/usr/libexec/thermalmonitord""",
r"""/usr/libexec/opendirectoryd""",
r"""/System/Library/PrivateFrameworks/ApplePushService.framework/apsd""",
r"""/System/Library/CoreServices/launchservicesd""",
r"""/usr/libexec/timed""",
r"""/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/Resources/usbmuxd -launchd""",
r"""/usr/sbin/securityd -i""",
r"""/usr/libexec/nesessionmanager""",
r"""/usr/libexec/CSCSupportd""",
r"""autofsd""",
r"""/usr/libexec/dasd""",
r"""/usr/sbin/distnoted daemon""",
r"""/System/Library/PrivateFrameworks/AppleCredentialManager.framework/AppleCredentialManagerDaemon""",
r"""/usr/libexec/dirhelper""",
r"""/System/Library/CoreServices/logind""",
r"""/System/Library/PrivateFrameworks/GenerationalStorage.framework/Versions/A/Support/revisiond""",
r"""/usr/sbin/KernelEventAgent""",
r"""/usr/libexec/usermanagerd -t 15""",
r"""/usr/sbin/bluetoothd""",
r"""/usr/sbin/notifyd""",
r"""/usr/libexec/sandboxd""",
r"""/usr/libexec/corebrightnessd --launchd""",
r"""/usr/libexec/AirPlayXPCHelper""",
r"""/System/Library/Frameworks/CoreMediaIO.framework/Versions/A/Resources/com.apple.cmio.registerassistantservice""",
r"""aslmanager""",
r"""/usr/libexec/logd_helper""",
r"""/System/Library/PrivateFrameworks/TCC.framework/Support/tccd system""",
r"""/usr/sbin/cfprefsd daemon""",
r"""/System/Library/PrivateFrameworks/SkyLight.framework/Resources/WindowServer -daemon""",
r"""/System/Library/PrivateFrameworks/CoreAnalytics.framework/Support/analyticsd""",
r"""/usr/libexec/runningboardd""",
r"""/System/Library/PrivateFrameworks/CoreDuetContext.framework/Resources/contextstored""",
r"""/System/Library/CoreServices/coreservicesd""",
r"""/usr/libexec/powerexperienced""",
r"""/usr/libexec/containermanagerd_system --runmode=privileged --user-container-mode=current --bundle-container-mode=global --bundle-container-owner=_appinstalld --system-container-mode=none""",
r"""/System/Library/CoreServices/TimeMachine/backupd-helper -launchd""",
r"""/usr/libexec/PowerUIAgent""",
r"""/usr/libexec/airportd""",
r"""/usr/sbin/coreaudiod""",
r"""/usr/libexec/trustdFileHelper""",
r"""/System/Library/PrivateFrameworks/PowerLog.framework/Versions/A/XPCServices/PerfPowerTelemetryClientRegistrationService.xpc/Contents/MacOS/PerfPowerTelemetryClientRegistrationService""",
r"""/System/Library/Frameworks/Security.framework/Versions/A/XPCServices/authd.xpc/Contents/MacOS/authd""",
r"""/usr/sbin/mDNSResponder""",
r"""/usr/sbin/distnoted agent""",
r"""/usr/sbin/distnoted agent""",
r"""/usr/libexec/mobileassetd""",
r"""/System/Library/PrivateFrameworks/SystemStatusServer.framework/Support/systemstatusd""",
r"""/usr/libexec/eligibilityd""",
r"""/usr/libexec/lsd runAsRoot""",
r"""/usr/libexec/hidd""",
r"""/usr/sbin/distnoted agent""",
r"""/usr/libexec/secinitd""",
r"""/usr/libexec/storagekitd""",
r"""/System/Library/Frameworks/CoreAudio.framework/Versions/A/XPCServices/com.apple.audio.DriverHelper.xpc/Contents/MacOS/com.apple.audio.DriverHelper""",
r"""/System/Library/Frameworks/AudioToolbox.framework/AudioComponentRegistrar -daemon""",
r"""/System/Library/PrivateFrameworks/BiomeStreams.framework/Support/biomed""",
r"""/usr/libexec/nehelper""",
r"""/usr/libexec/syspolicyd""",
r"""/usr/libexec/symptomsd""",
r"""/System/Library/Frameworks/AudioToolbox.framework/XPCServices/com.apple.audio.SandboxHelper.xpc/Contents/MacOS/com.apple.audio.SandboxHelper""",
r"""/usr/libexec/audioclocksyncd""",
r"""/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/XPCServices/csnameddatad.xpc/Contents/MacOS/csnameddatad""",
r"""/usr/sbin/mDNSResponderHelper""",
r"""/usr/libexec/colorsync.displayservices""",
r"""/usr/sbin/distnoted agent""",
r"""/System/Library/Frameworks/ColorSync.framework/Versions/A/XPCServices/com.apple.ColorSyncXPCAgent.xpc/Contents/MacOS/com.apple.ColorSyncXPCAgent""",
r"""/usr/libexec/colorsyncd""",
r"""/System/Library/Frameworks/SystemExtensions.framework/Versions/A/Helpers/sysextd""",
r"""/System/Library/Frameworks/Security.framework/Versions/A/XPCServices/com.apple.CodeSigningHelper.xpc/Contents/MacOS/com.apple.CodeSigningHelper""",
r"""/usr/libexec/modelmanagerd""",
r"""/System/Library/DriverExtensions/com.apple.DriverKit-AppleBCMWLAN.dext/com.apple.DriverKit-AppleBCMWLAN com.apple.bcmwlan 0x100000bc1 com.apple.DriverKit-AppleBCMWLAN""",
r"""/System/Library/CoreServices/Software Update.app/Contents/Resources/suhelperd""",
r"""/System/Library/DriverExtensions/com.apple.DriverKit-IOUserDockChannelSerial.dext/com.apple.DriverKit-IOUserDockChannelSerial com.apple.IOUserDockChannelSerial 0x100000cbc com.apple.DriverKit-IOUserDockChannelSerial""",
r"""/System/Library/DriverExtensions/com.apple.AppleUserHIDDrivers.dext/com.apple.AppleUserHIDDrivers com.apple.driverkit.AppleUserHIDDrivers 0x100000cbd com.apple.AppleUserHIDDrivers""",
r"""/System/Library/PrivateFrameworks/AppleDeviceQuerySupport.framework/Versions/A/XPCServices/AppleDeviceQueryService.xpc/Contents/MacOS/AppleDeviceQueryService""",
r"""/usr/libexec/nsurlsessiond --privileged""",
r"""/System/Library/CoreServices/liquiddetectiond.app/liquiddetectiond""",
r"""/usr/libexec/apfsd""",
r"""/usr/libexec/cryptexd""",
r"""/usr/libexec/usbd""",
r"""/usr/libexec/ApplicationFirewall/socketfilterfw""",
r"""/usr/libexec/biometrickitd --launchd""",
r"""/System/Library/PrivateFrameworks/ModelCatalogRuntime.framework/Versions/A/modelcatalogd""",
r"""/usr/libexec/cameracaptured""",
r"""/System/Library/Frameworks/CoreMediaIO.framework/Versions/A/Resources/UVCAssistant.systemextension/Contents/MacOS/UVCAssistant""",
r"""/usr/sbin/appleh16camerad""",
r"""/usr/libexec/audioanalyticsd""",
r"""/usr/libexec/countryd""",
r"""/usr/sbin/distnoted agent""",
r"""/usr/libexec/secinitd""",
r"""/usr/libexec/secinitd""",
r"""/usr/sbin/cfprefsd agent""",
r"""/usr/sbin/cfprefsd agent""",
r"""/System/Library/CoreServices/Software Update.app/Contents/Resources/softwareupdated""",
r"""/usr/libexec/containermanagerd --runmode=agent --user-container-mode=current --bundle-container-mode=proxy --system-container-mode=none""",
r"""/usr/libexec/containermanagerd --runmode=agent --user-container-mode=current --bundle-container-mode=proxy --system-container-mode=none""",
r"""/usr/sbin/distnoted agent""",
r"""/usr/libexec/tzlinkd""",
r"""/System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Resources/backgroundtaskmanagementd -daemon""",
r"""/usr/libexec/symptomsd-diag""",
r"""/Library/Apple/System/Library/CoreServices/XProtect.app/Contents/XPCServices/XProtectPluginService.xpc/Contents/MacOS/XProtectPluginService""",
r"""/usr/libexec/rtcreportingd""",
r"""/usr/sbin/WirelessRadioManagerd""",
r"""/usr/libexec/findmybeaconingd""",
r"""/System/Library/CoreServices/TimeMachine/backupd""",
r"""/usr/libexec/mobileactivationd""",
r"""/usr/libexec/securityd_system""",
r"""/System/Library/PrivateFrameworks/MobileAccessoryUpdater.framework/XPCServices/UARPUpdaterServiceUSBPD.xpc/Contents/MacOS/UARPUpdaterServiceUSBPD""",
r"""/System/Library/PrivateFrameworks/MobileAccessoryUpdater.framework/XPCServices/UARPUpdaterServiceAFU.xpc/Contents/MacOS/UARPUpdaterServiceAFU""",
r"""/System/Library/PrivateFrameworks/MobileAccessoryUpdater.framework/XPCServices/UARPUpdaterServiceDisplay.xpc/Contents/MacOS/UARPUpdaterServiceDisplay""",
r"""/System/Library/PrivateFrameworks/MobileAccessoryUpdater.framework/XPCServices/UARPUpdaterServiceDFU.xpc/Contents/MacOS/UARPUpdaterServiceDFU""",
r"""/System/Library/PrivateFrameworks/MobileAccessoryUpdater.framework/XPCServices/UARPUpdaterServiceLegacyAudio.xpc/Contents/MacOS/UARPUpdaterServiceLegacyAudio""",
r"""/System/Library/PrivateFrameworks/MobileAccessoryUpdater.framework/XPCServices/UARPUpdaterServiceHID.xpc/Contents/MacOS/UARPUpdaterServiceHID""",
r"""/usr/sbin/distnoted agent""",
r"""/System/Library/PrivateFrameworks/MobileAccessoryUpdater.framework/XPCServices/ThunderboltAccessoryUpdaterService.xpc/Contents/MacOS/ThunderboltAccessoryUpdaterService""",
r"""/usr/libexec/secinitd""",
r"""/usr/sbin/cfprefsd agent""",
r"""/System/Library/PrivateFrameworks/SystemAdministration.framework/XPCServices/writeconfig.xpc/Contents/MacOS/writeconfig""",
r"""/usr/libexec/containermanagerd --runmode=agent --user-container-mode=current --bundle-container-mode=proxy --system-container-mode=none""",
r"""/usr/libexec/wifip2pd""",
r"""/System/Library/PrivateFrameworks/WiFiPolicy.framework/XPCServices/WiFiCloudAssetsXPCService.xpc/Contents/MacOS/WiFiCloudAssetsXPCService""",
r"""/System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/XPCServices/com.apple.geod.xpc/Contents/MacOS/com.apple.geod""",
r"""/usr/libexec/containermanagerd --runmode=agent --user-container-mode=current --bundle-container-mode=proxy --system-container-mode=none""",
r"""/System/Library/CoreServices/ReportCrash daemon""",
r"""/System/Library/PrivateFrameworks/CoreSymbolication.framework/coresymbolicationd""",
r"""/usr/libexec/searchpartyd""",
r"""/usr/libexec/wifianalyticsd""",
r"""/usr/libexec/locationd""",
r"""/System/Library/CoreServices/appleeventsd --server""",
r"""/System/Library/Frameworks/NetFS.framework/Versions/A/XPCServices/PlugInLibraryService.xpc/Contents/MacOS/PlugInLibraryService""",
r"""/usr/libexec/bootinstalld""",
r"""/usr/sbin/distnoted agent""",
r"""/System/Library/PrivateFrameworks/MobileSoftwareUpdate.framework/Versions/A/XPCServices/com.apple.MobileSoftwareUpdate.CleanupPreparePathService.xpc/Contents/MacOS/com.apple.MobileSoftwareUpdate.CleanupPreparePathService""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mds_stores""",
r"""/usr/sbin/distnoted agent""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdbulkimport -s mdworker-bundle -c MDSImporterBundleFinder -m com.apple.metadata.mdbulkimport""",
r"""/usr/libexec/sysmond""",
r"""/usr/sbin/systemstats --logger-helper /private/var/db/systemstats""",
r"""/usr/sbin/spindump""",
r"""/System/Library/CoreServices/SubmitDiagInfo server-init""",
r"""/usr/libexec/fskit_helper""",
r"""/System/Library/CoreServices/iconservicesagent runAsRoot""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/usr/sbin/systemsoundserverd""",
r"""/System/Library/Frameworks/GSS.framework/Helpers/GSSCred""",
r"""/System/Library/PrivateFrameworks/MobileInstallation.framework/Support/appinstalld""",
r"""/System/Library/PrivateFrameworks/MobileInstallation.framework/XPCServices/com.apple.MobileInstallationHelperService.xpc/Contents/MacOS/com.apple.MobileInstallationHelperService""",
r"""/usr/sbin/distnoted agent""",
r"""/usr/libexec/aneuserd""",
r"""/usr/libexec/aned""",
r"""/usr/libexec/online-auth-agent""",
r"""/System/Library/Frameworks/LocalAuthentication.framework/Support/coreauthd""",
r"""/usr/libexec/applekeystored""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/usr/libexec/gamecontrollerd""",
r"""/usr/libexec/seld""",
r"""/usr/sbin/distnoted agent""",
r"""/usr/libexec/gamepolicyd""",
r"""/System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Support/awdd""",
r"""/System/Library/PrivateFrameworks/CloudKitDaemon.framework/Support/cloudd --system""",
r"""/System/Library/CoreServices/osanalyticshelper server-init""",
r"""/System/Library/PrivateFrameworks/AppSSO.framework/Support/AppSSODaemon""",
r"""/usr/libexec/findmydeviced""",
r"""/System/Library/PrivateFrameworks/CoreADI.framework/adid""",
r"""/System/Library/CoreServices/diagnosticservicesd""",
r"""/System/Library/Frameworks/CryptoTokenKit.framework/ctkd -st""",
r"""/System/Library/PrivateFrameworks/TVIdleServices.framework/idleassetsd""",
r"""/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/XPCServices/com.apple.hiservices-xpcservice.xpc/Contents/MacOS/com.apple.hiservices-xpcservice""",
r"""/System/Library/DriverExtensions/IOUserBluetoothSerialDriver.dext/IOUserBluetoothSerialDriver com.apple.IOUserBluetoothSerialDriver 0x100000ee3 com.apple.IOUserBluetoothSerialDriver""",
r"""/System/Library/PrivateFrameworks/AppleNeuralEngine.framework/XPCServices/ANECompilerService.xpc/Contents/MacOS/ANECompilerService""",
r"""/usr/libexec/nearbyd""",
r"""/usr/libexec/nfcd""",
r"""/System/Library/PrivateFrameworks/NearFieldPrivateServices.framework/Versions/A/XPCServices/NFRestoreService.xpc/Contents/MacOS/NFRestoreService""",
r"""/usr/sbin/distnoted agent""",
r"""/usr/sbin/distnoted agent""",
r"""/usr/sbin/filecoordinationd""",
r"""/System/Library/PrivateFrameworks/NearFieldPrivateServices.framework/Versions/A/XPCServices/NFStorageServer.xpc/Contents/MacOS/NFStorageServer""",
r"""/System/Library/PrivateFrameworks/CloudTelemetry.framework/Versions/A/XPCServices/CloudTelemetryService.xpc/Contents/MacOS/CloudTelemetryService""",
r"""/System/Library/PrivateFrameworks/XprotectFramework.framework/Versions/A/XPCServices/XProtectBridgeService.xpc/Contents/MacOS/XProtectBridgeService""",
r"""/usr/libexec/audiomxd""",
r"""/System/Library/PrivateFrameworks/RemoteManagement.framework/remotemanagementd""",
r"""/usr/sbin/distnoted agent""",
r"""/usr/libexec/ASPCarryLog""",
r"""/usr/libexec/betaenrollmentd""",
r"""/usr/libexec/ospredictiond""",
r"""/System/Library/PrivateFrameworks/CloudTelemetry.framework/Versions/A/XPCServices/CloudTelemetryService.xpc/Contents/MacOS/CloudTelemetryService""",
r"""/System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/XPCServices/com.apple.geod.xpc/Contents/MacOS/com.apple.geod""",
r"""/System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/XPCServices/com.apple.geod.xpc/Contents/MacOS/com.apple.geod""",
r"""/System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/XPCServices/com.apple.geod.xpc/Contents/MacOS/com.apple.geod""",
r"""/System/Library/Frameworks/CryptoTokenKit.framework/ctkahp.bundle/Contents/MacOS/ctkahp -d""",
r"""/usr/libexec/mmaintenanced""",
r"""/System/Library/Frameworks/AudioToolbox.framework/XPCServices/com.apple.audio.SandboxHelper.xpc/Contents/MacOS/com.apple.audio.SandboxHelper""",
r"""/System/Library/PrivateFrameworks/SharePointManagement.framework/XPCServices/SharePointManagementService.xpc/Contents/MacOS/SharePointManagementService""",
r"""/usr/sbin/distnoted agent""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdbulkimport -s mdworker-bundle -c MDSImporterBundleFinder -m com.apple.metadata.mdbulkimport""",
r"""/usr/sbin/cfprefsd agent""",
r"""/usr/libexec/pkd""",
r"""/usr/libexec/lsd""",
r"""/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/XPCServices/csnameddatad.xpc/Contents/MacOS/csnameddatad""",
r"""/System/Library/PrivateFrameworks/FindMyMac.framework/Resources/FindMyMacd""",
r"""/System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow console""",
r"""/System/Library/PrivateFrameworks/CoreKDL.framework/Support/corekdld""",
r"""/usr/libexec/UserEventAgent (Aqua)""",
r"""/System/Library/CoreServices/ControlCenter.app/Contents/MacOS/ControlCenter""",
r"""/System/Library/PrivateFrameworks/CoreDuetContext.framework/Resources/ContextStoreAgent""",
r"""/usr/libexec/knowledge-agent""",
r"""/usr/libexec/ContinuityCaptureAgent server""",
r"""/usr/sbin/universalaccessd launchd -s""",
r"""/usr/libexec/pboard""",
r"""/System/Library/Frameworks/CoreTelephony.framework/Support/CommCenter -L""",
r"""/System/Library/CoreServices/APFSUserAgent""",
r"""/usr/libexec/rapportd""",
r"""/usr/libexec/nsurlsessiond""",
r"""/usr/sbin/usernoted""",
r"""/usr/libexec/routined LAUNCHED_BY_LAUNCHD""",
r"""/System/Library/CoreServices/WiFiAgent.app/Contents/MacOS/WiFiAgent""",
r"""/usr/libexec/secinitd""",
r"""/System/Library/CoreServices/CoreLocationAgent.app/Contents/MacOS/CoreLocationAgent""",
r"""/usr/libexec/secd""",
r"""/System/Library/PrivateFrameworks/VoiceShortcuts.framework/Versions/A/Support/siriactionsd""",
r"""/usr/libexec/containermanagerd --runmode=agent --user-container-mode=current --bundle-container-mode=proxy --system-container-mode=none""",
r"""/System/Library/PrivateFrameworks/TelephonyUtilities.framework/callservicesd""",
r"""/System/Library/PrivateFrameworks/SyncedDefaults.framework/Support/syncdefaultsd""",
r"""/System/Library/PrivateFrameworks/IDS.framework/identityservicesd.app/Contents/MacOS/identityservicesd""",
r"""/System/Library/Frameworks/Accounts.framework/Versions/A/Support/accountsd""",
r"""/System/Library/PrivateFrameworks/CloudKitDaemon.framework/Support/cloudd""",
r"""/System/Library/PrivateFrameworks/UserNotificationsCore.framework/Support/usernotificationsd""",
r"""/System/Library/PrivateFrameworks/TCC.framework/Support/tccd""",
r"""/System/Library/PrivateFrameworks/CoreAnalytics.framework/Support/analyticsagent""",
r"""/System/Library/PrivateFrameworks/UsageTracking.framework/Versions/A/UsageTrackingAgent""",
r"""/usr/libexec/linkd""",
r"""/System/Library/PrivateFrameworks/ContinuousDialogManagerService.framework/assistant_cdmd""",
r"""/System/Library/PrivateFrameworks/NewDeviceOutreach.framework/ndoagent""",
r"""/usr/libexec/siriknowledged""",
r"""/System/Library/PrivateFrameworks/CoreFollowUp.framework/Versions/A/Support/followupd""",
r"""/System/Library/Frameworks/ManagedSettings.framework/Versions/A/ManagedSettingsAgent""",
r"""/System/Library/PrivateFrameworks/DoNotDisturbServer.framework/Support/donotdisturbd""",
r"""/usr/libexec/searchpartyuseragent""",
r"""/usr/libexec/findmylocateagent""",
r"""/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/mediaanalysisd""",
r"""/System/Library/PrivateFrameworks/CoreCDP.framework/Versions/A/Resources/cdpd""",
r"""/usr/libexec/triald""",
r"""/System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/XPCServices/com.apple.geod.xpc/Contents/MacOS/com.apple.geod""",
r"""/usr/libexec/icloudmailagent""",
r"""/System/Library/PrivateFrameworks/FileProvider.framework/Support/fileproviderd""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/corespotlightd""",
r"""/System/Library/PrivateFrameworks/CacheDelete.framework/deleted""",
r"""/System/Library/Frameworks/LocalAuthentication.framework/Support/coreauthd""",
r"""/System/Library/CoreServices/sharedfilelistd""",
r"""/System/Library/PrivateFrameworks/BiomeStreams.framework/Support/BiomeAgent""",
r"""/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/Versions/A/Support/photolibraryd""",
r"""/System/Library/PrivateFrameworks/ReplicatorCore.framework/Support/replicatord""",
r"""/System/Library/CoreServices/NotificationCenter.app/Contents/MacOS/NotificationCenter""",
r"""/System/Library/PrivateFrameworks/SocialLayer.framework/sociallayerd.app/Contents/MacOS/sociallayerd""",
r"""/System/Library/PrivateFrameworks/CalendarDaemon.framework/Support/calaccessd""",
r"""/System/Library/CoreServices/iconservicesagent""",
r"""/System/Library/CoreServices/talagentd""",
r"""/System/Library/CoreServices/WindowManager.app/Contents/MacOS/WindowManager""",
r"""/System/Library/PrivateFrameworks/ScreenTimeCore.framework/Versions/A/ScreenTimeAgent""",
r"""/System/Library/PrivateFrameworks/AppleMediaServices.framework/Resources/amsaccountsd""",
r"""/usr/libexec/intelligentroutingd""",
r"""/System/Library/CoreServices/audioaccessoryd""",
r"""/System/Library/PrivateFrameworks/MobileTimer.framework/Executables/mobiletimerd""",
r"""/usr/libexec/replayd""",
r"""/System/Library/Frameworks/AudioToolbox.framework/AudioComponentRegistrar""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/usr/libexec/transparencyd""",
r"""/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/XPCServices/com.apple.hiservices-xpcservice.xpc/Contents/MacOS/com.apple.hiservices-xpcservice""",
r"""/usr/libexec/dmd""",
r"""/System/Library/PrivateFrameworks/ChronoCore.framework/Support/chronod""",
r"""/System/Library/PrivateFrameworks/AppleMediaServicesUI.framework/amsengagementd""",
r"""/System/Library/PrivateFrameworks/WiFiPolicy.framework/XPCServices/WiFiCloudAssetsXPCService.xpc/Contents/MacOS/WiFiCloudAssetsXPCService""",
r"""/System/Library/PrivateFrameworks/FamilyCircle.framework/Versions/A/Resources/familycircled""",
r"""/System/Library/CoreServices/UIKitSystem.app/Contents/MacOS/UIKitSystem system_app_start""",
r"""/usr/libexec/neagent""",
r"""/usr/libexec/appleaccountd""",
r"""/System/Library/PrivateFrameworks/StatusKit.framework/StatusKitAgent""",
r"""/usr/libexec/milod""",
r"""/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/XPCServices/com.apple.DictionaryServiceHelper.xpc/Contents/MacOS/com.apple.DictionaryServiceHelper""",
r"""/System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Support/fontworker""",
r"""/System/Library/PrivateFrameworks/IMCore.framework/imagent.app/Contents/MacOS/imagent""",
r"""/System/Library/PrivateFrameworks/Stickers.framework/Support/stickersd""",
r"""/System/Library/PrivateFrameworks/IMDPersistence.framework/XPCServices/IMDPersistenceAgent.xpc/Contents/MacOS/IMDPersistenceAgent""",
r"""/System/Library/PrivateFrameworks/CloudTelemetry.framework/Versions/A/XPCServices/CloudTelemetryService.xpc/Contents/MacOS/CloudTelemetryService""",
r"""/System/Library/PrivateFrameworks/ContactsDonation.framework/Versions/A/Support/contactsdonationagent""",
r"""/System/Library/Frameworks/CryptoTokenKit.framework/ctkd -tw""",
r"""/System/Library/PrivateFrameworks/ContextKit.framework/Versions/A/XPCServices/ContextService.xpc/Contents/MacOS/ContextService""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/managedcorespotlightd""",
r"""/System/Library/PrivateFrameworks/TelephonyUtilities.framework/XPCServices/com.apple.FaceTime.FTConversationService.xpc/Contents/MacOS/com.apple.FaceTime.FTConversationService""",
r"""/System/Library/PrivateFrameworks/HomeKitDaemon.framework/Support/homed""",
r"""/System/Library/PrivateFrameworks/UserActivity.framework/Agents/useractivityd""",
r"""/System/Library/PrivateFrameworks/MediaRemote.framework/Support/mediaremoteagent""",
r"""/System/Library/PrivateFrameworks/CallHistory.framework/Support/CallHistorySyncHelper""",
r"""/usr/libexec/avconferenced""",
r"""/System/Library/PrivateFrameworks/AssistantServices.framework/Versions/A/Support/assistantd""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/System/Library/CoreServices/ScopedBookmarkAgent""",
r"""/System/Library/CoreServices/ReportCrash agent""",
r"""/System/Library/Frameworks/NetFS.framework/Versions/A/XPCServices/PlugInLibraryService.xpc/Contents/MacOS/PlugInLibraryService""",
r"""/System/Library/PrivateFrameworks/CloudTelemetry.framework/Versions/A/XPCServices/CloudTelemetryService.xpc/Contents/MacOS/CloudTelemetryService""",
r"""/System/Library/PrivateFrameworks/PhotoAnalysis.framework/Versions/A/Support/photoanalysisd""",
r"""/System/Library/PrivateFrameworks/Categories.framework/Versions/A/XPCServices/CategoriesService.xpc/Contents/MacOS/CategoriesService""",
r"""/System/Library/PrivateFrameworks/AXAssetLoader.framework/Support/axassetsd""",
r"""/usr/libexec/networkserviceproxy""",
r"""/System/Library/PrivateFrameworks/iCloudNotification.framework/iCloudNotificationAgent""",
r"""/usr/libexec/gamecontrolleragentd""",
r"""/System/Library/Frameworks/CoreSpotlight.framework/spotlightknowledged -u""",
r"""/System/Library/PrivateFrameworks/People.framework/peopled""",
r"""/usr/libexec/proactived""",
r"""/System/Library/PrivateFrameworks/DataAccess.framework/Support/dataaccessd""",
r"""/System/Library/CoreServices/pbs""",
r"""/System/Library/PrivateFrameworks/CoreParsec.framework/parsecd""",
r"""/System/Library/PrivateFrameworks/iTunesCloud.framework/Support/itunescloudd""",
r"""/usr/libexec/MTLAssetUpgraderD""",
r"""/usr/libexec/swcd""",
r"""/System/Library/Frameworks/MediaExtension.framework/Versions/A/Helpers/MENotificationAgent""",
r"""/System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Support/BackgroundTaskManagementAgent.app/Contents/MacOS/BackgroundTaskManagementAgent""",
r"""/System/Library/PrivateFrameworks/CascadeSets.framework/Versions/A/XPCServices/SetStoreUpdateService.xpc/Contents/MacOS/SetStoreUpdateService""",
r"""/System/Library/PrivateFrameworks/CacheDelete.framework/deleted_helper""",
r"""/System/Applications/System Settings.app/Contents/PlugIns/csimporter.appex/Contents/MacOS/csimporter -AppleLanguages ("en-US")""",
r"""/System/Applications/Books.app/Contents/PlugIns/BooksSpotlightExtension.appex/Contents/MacOS/BooksSpotlightExtension -AppleLanguages ("en-US")""",
r"""/System/Applications/Podcasts.app/Contents/PlugIns/com.apple.podcasts.SpotlightIndexExtension.appex/Contents/MacOS/com.apple.podcasts.SpotlightIndexExtension -AppleLanguages ("en-US")""",
r"""/System/Library/PrivateFrameworks/IntlPreferences.framework/Support/localizationswitcherd""",
r"""/System/Library/Frameworks/ExtensionFoundation.framework/Versions/A/XPCServices/extensionkitservice.xpc/Contents/MacOS/extensionkitservice""",
r"""/System/Applications/News.app/Contents/PlugIns/NewsTag.appex/Contents/MacOS/NewsTag""",
r"""/System/Applications/Tips.app/Contents/PlugIns/TipsWidgetExtension.appex/Contents/MacOS/TipsWidgetExtension""",
r"""/System/Applications/Stocks.app/Contents/PlugIns/StocksWidget.appex/Contents/MacOS/StocksWidget""",
r"""/System/Applications/FindMy.app/Contents/PlugIns/FindMyWidgetItems.appex/Contents/MacOS/FindMyWidgetItems""",
r"""/System/Applications/Clock.app/Contents/PlugIns/WorldClockWidget.appex/Contents/MacOS/WorldClockWidget""",
r"""/System/Applications/Home.app/Contents/PlugIns/HomeEnergyWidgetsExtension.appex/Contents/MacOS/HomeEnergyWidgetsExtension""",
r"""/System/Applications/News.app/Contents/PlugIns/NewsTodayIntents.appex/Contents/MacOS/NewsTodayIntents -AppleLanguages ("en-US")""",
r"""/System/Applications/FindMy.app/Contents/PlugIns/FindMyWidgetPeople.appex/Contents/MacOS/FindMyWidgetPeople""",
r"""/System/Applications/Podcasts.app/Contents/PlugIns/PodcastsWidget.appex/Contents/MacOS/PodcastsWidget""",
r"""/System/Applications/Photos.app/Contents/PlugIns/PhotosReliveWidget.appex/Contents/MacOS/PhotosReliveWidget""",
r"""/System/Library/CoreServices/Screen Time.app/Contents/PlugIns/ScreenTimeWidgetExtension.appex/Contents/MacOS/ScreenTimeWidgetExtension""",
r"""/System/Library/CoreServices/PeopleViewService.app/Contents/PlugIns/PeopleWidget_macOSExtension.appex/Contents/MacOS/PeopleWidget_macOSExtension""",
r"""/System/Library/ExtensionKit/Extensions/SoundIntentsExtension.appex/Contents/MacOS/SoundIntentsExtension""",
r"""/System/Applications/Reminders.app/Contents/PlugIns/RemindersWidgetExtension.appex/Contents/MacOS/RemindersWidgetExtension""",
r"""/usr/libexec/AssetCache/AssetCache""",
r"""/System/Library/CoreServices/diagnostics_agent""",
r"""/System/Library/PrivateFrameworks/AppStoreDaemon.framework/Support/appstoreagent""",
r"""/System/Library/CoreServices/WallpaperAgent.app/Contents/MacOS/WallpaperAgent""",
r"""/System/Library/PrivateFrameworks/GeoServices.framework/geodMachServiceBridge""",
r"""/System/Library/PrivateFrameworks/PackageKit.framework/Resources/installd""",
r"""/System/Library/PrivateFrameworks/PackageKit.framework/Resources/system_installd""",
r"""/System/Library/Frameworks/QuickLookThumbnailing.framework/Support/com.apple.quicklook.ThumbnailsAgent""",
r"""/System/Applications/Calendar.app/Contents/PlugIns/CalendarWidgetExtension.appex/Contents/MacOS/CalendarWidgetExtension""",
r"""/System/Applications/VoiceMemos.app/Contents/PlugIns/VoiceMemosSettingsWidgetExtension.appex/Contents/MacOS/VoiceMemosSettingsWidgetExtension""",
r"""/System/Library/CoreServices/Batteries.app/Contents/PlugIns/BatteriesAvocadoWidgetExtension.appex/Contents/MacOS/BatteriesAvocadoWidgetExtension""",
r"""/System/Applications/Home.app/Contents/PlugIns/HomeWidget.appex/Contents/MacOS/HomeWidget""",
r"""/System/Library/PrivateFrameworks/AssetCacheServicesExtensions.framework/XPCServices/AssetCacheTetheratorService.xpc/Contents/MacOS/AssetCacheTetheratorService""",
r"""/System/Library/PrivateFrameworks/CoreSpeech.framework/corespeechd""",
r"""/System/Library/CoreServices/CoreServicesUIAgent.app/Contents/MacOS/CoreServicesUIAgent""",
r"""/System/Library/Frameworks/Speech.framework/Versions/A/XPCServices/localspeechrecognition.xpc/Contents/MacOS/localspeechrecognition""",
r"""/System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/XPCServices/ViewBridgeAuxiliary.xpc/Contents/MacOS/ViewBridgeAuxiliary""",
r"""/System/Library/PrivateFrameworks/iCloudDriveCore.framework/Versions/A/Support/bird""",
r"""/System/Library/PrivateFrameworks/LockdownMode.framework/Versions/A/XPCServices/lockdownmoded""",
r"""/System/Library/Frameworks/ExtensionFoundation.framework/Versions/A/XPCServices/extensionkitservice.xpc/Contents/MacOS/extensionkitservice""",
r"""/System/Library/ExtensionKit/Extensions/WallpaperVideoExtension.appex/Contents/MacOS/WallpaperVideoExtension""",
r"""/usr/sbin/distnoted agent""",
r"""/System/Library/Frameworks/VideoToolbox.framework/Versions/A/XPCServices/VTDecoderXPCService.xpc/Contents/MacOS/VTDecoderXPCService""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/System/Library/Frameworks/CryptoTokenKit.framework/ctkahp.bundle/Contents/MacOS/ctkahp""",
r"""/usr/libexec/sharingd""",
r"""/System/Library/PrivateFrameworks/InstallCoordination.framework/Support/installcoordinationd""",
r"""/System/Library/PrivateFrameworks/AppStoreDaemon.framework/Versions/A/XPCServices/com.apple.AppStoreDaemon.StorePrivilegedODRService.xpc/Contents/MacOS/com.apple.AppStoreDaemon.StorePrivilegedODRService""",
r"""/usr/libexec/promotedcontentd""",
r"""/usr/libexec/fairplaydeviceidentityd""",
r"""/System/Library/PrivateFrameworks/CoreFP.framework/Versions/A/fairplayd""",
r"""/usr/libexec/bluetoothuserd""",
r"""/System/Applications/Reminders.app/Contents/PlugIns/RemindersSpotlightIndexExtension.appex/Contents/MacOS/RemindersSpotlightIndexExtension -AppleLanguages ("en-US")""",
r"""/System/Applications/Notes.app/Contents/PlugIns/com.apple.Notes.SpotlightIndexExtension.appex/Contents/MacOS/com.apple.Notes.SpotlightIndexExtension -AppleLanguages ("en-US")""",
r"""/System/Applications/Mail.app/Contents/PlugIns/com.apple.mail.SpotlightIndexExtension.appex/Contents/MacOS/com.apple.mail.SpotlightIndexExtension -AppleLanguages ("en-US")""",
r"""/System/Library/CoreServices/CrashReporterSupportHelper server-init""",
r"""/usr/libexec/triald_system""",
r"""/System/Library/Frameworks/AudioToolbox.framework/XPCServices/com.apple.audio.ComponentTagHelper.xpc/Contents/MacOS/com.apple.audio.ComponentTagHelper""",
r"""/System/Library/PrivateFrameworks/TextToSpeech.framework/PlugIns/SiriAUSP.appex/Contents/MacOS/SiriAUSP -AppleLanguages ("en-US")""",
r"""/System/Library/PrivateFrameworks/TextToSpeechMauiSupport.framework/Versions/A/PlugIns/MauiAUSP.appex/Contents/MacOS/MauiAUSP -AppleLanguages ("en-US")""",
r"""/System/Library/PrivateFrameworks/MacinTalk.framework/Versions/A/PlugIns/WardaSynthesizer_arm64.appex/Contents/MacOS/WardaSynthesizer_arm64 -AppleLanguages ("en-US")""",
r"""/System/Library/PrivateFrameworks/MacinTalk.framework/Versions/A/PlugIns/MacinTalkAUSP.appex/Contents/MacOS/MacinTalkAUSP -AppleLanguages ("en-US")""",
r"""/System/Library/PrivateFrameworks/TextToSpeechKonaSupport.framework/Versions/A/PlugIns/KonaSynthesizer.appex/Contents/MacOS/KonaSynthesizer -AppleLanguages ("en-US")""",
r"""/System/Library/Frameworks/AudioToolbox.framework/XPCServices/com.apple.audio.SandboxHelper.xpc/Contents/MacOS/com.apple.audio.SandboxHelper""",
r"""/System/Library/Frameworks/AudioToolbox.framework/XPCServices/com.apple.audio.SandboxHelper.xpc/Contents/MacOS/com.apple.audio.SandboxHelper""",
r"""/System/Library/Frameworks/AudioToolbox.framework/XPCServices/com.apple.audio.SandboxHelper.xpc/Contents/MacOS/com.apple.audio.SandboxHelper""",
r"""/System/Library/Frameworks/AudioToolbox.framework/XPCServices/AUCrashHandlerService.xpc/Contents/MacOS/AUCrashHandlerService""",
r"""/System/Library/Frameworks/AudioToolbox.framework/XPCServices/com.apple.audio.SandboxHelper.xpc/Contents/MacOS/com.apple.audio.SandboxHelper""",
r"""/System/Library/PrivateFrameworks/TextToSpeechVoiceBankingSupport.framework/Support/voicebankingd""",
r"""/System/Library/PrivateFrameworks/SiriTTSService.framework/Versions/A/XPCServices/com.apple.SiriTTSService.TrialProxy.xpc/Contents/MacOS/com.apple.SiriTTSService.TrialProxy""",
r"""/System/Library/Frameworks/AudioToolbox.framework/XPCServices/com.apple.audio.SandboxHelper.xpc/Contents/MacOS/com.apple.audio.SandboxHelper""",
r"""/System/Library/PrivateFrameworks/SiriTTSService.framework/Versions/A/XPCServices/com.apple.SiriTTSService.TrialProxy.xpc/Contents/MacOS/com.apple.SiriTTSService.TrialProxy""",
r"""/System/Applications/Weather.app/Contents/PlugIns/WeatherIntents.appex/Contents/MacOS/WeatherIntents -AppleLanguages ("en-US")""",
r"""/System/Library/PrivateFrameworks/MobileTimer.framework/PlugIns/MobileTimerIntents.appex/Contents/MacOS/MobileTimerIntents -AppleLanguages ("en-US")""",
r"""/System/Library/CoreServices/Screen Time.app/Contents/PlugIns/ScreenTimeWidgetIntentsExtension.appex/Contents/MacOS/ScreenTimeWidgetIntentsExtension -AppleLanguages ("en-US")""",
r"""/System/Library/CoreServices/PeopleViewService.app/Contents/PlugIns/SelectPerson_iOS.appex/Contents/MacOS/SelectPerson_iOS -AppleLanguages ("en-US")""",
r"""/System/Applications/Reminders.app/Contents/PlugIns/RemindersIntentsExtension.appex/Contents/MacOS/RemindersIntentsExtension -AppleLanguages ("en-US")""",
r"""/System/Library/PrivateFrameworks/CalendarWidget.framework/PlugIns/IntentsExtension.appex/Contents/MacOS/IntentsExtension -AppleLanguages ("en-US")""",
r"""/System/Library/PrivateFrameworks/GenerativeExperiencesRuntime.framework/Versions/A/generativeexperiencesd""",
r"""/System/Applications/Notes.app/Contents/PlugIns/com.apple.Notes.IntentsExtension.appex/Contents/MacOS/com.apple.Notes.IntentsExtension -AppleLanguages ("en-US")""",
r"""/System/Library/Frameworks/FinanceKit.framework/financed""",
r"""/System/Library/PrivateFrameworks/EmailDaemon.framework/Versions/A/maild""",
r"""/System/Library/Frameworks/ExtensionFoundation.framework/Versions/A/XPCServices/extensionkitservice.xpc/Contents/MacOS/extensionkitservice""",
r"""/System/Applications/Calendar.app/Contents/Extensions/CalendarIntentsExtension.appex/Contents/MacOS/CalendarIntentsExtension""",
r"""/System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app/Contents/Extensions/SafariLinkExtension.appex/Contents/MacOS/SafariLinkExtension""",
r"""/System/Applications/Messages.app/Contents/Extensions/MessagesActionExtension.appex/Contents/MacOS/MessagesActionExtension""",
r"""/System/Library/Frameworks/ExtensionFoundation.framework/Versions/A/XPCServices/extensionkitservice.xpc/Contents/MacOS/extensionkitservice""",
r"""/System/Library/PrivateFrameworks/ModelCatalogRuntime.framework/Versions/A/ModelCatalogAgent""",
r"""/usr/libexec/diagnosticspushd""",
r"""/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/siriinferenced""",
r"""/System/Library/PrivateFrameworks/SiriSuggestionsSupport.framework/Versions/A/XPCServices/SiriSuggestionsBookkeepingService.xpc/Contents/MacOS/SiriSuggestionsBookkeepingService""",
r"""/usr/libexec/diagnosticextensionsd""",
r"""/System/Library/PrivateFrameworks/SiriAnalytics.framework/Versions/A/XPCServices/SAExtensionOrchestrator.xpc/Contents/MacOS/SAExtensionOrchestrator""",
r"""/System/Library/Frameworks/ExtensionFoundation.framework/Versions/A/XPCServices/extensionkitservice.xpc/Contents/MacOS/extensionkitservice""",
r"""/System/Library/ExtensionKit/Extensions/IFTranscriptSELFIngestor.appex/Contents/MacOS/IFTranscriptSELFIngestor""",
r"""/System/Library/ExtensionKit/Extensions/IFTelemetrySELFIngestor.appex/Contents/MacOS/IFTelemetrySELFIngestor""",
r"""/System/Library/ExtensionKit/Extensions/GMSSELFIngestor.appex/Contents/MacOS/GMSSELFIngestor""",
r"""/System/Library/ExtensionKit/Extensions/BiomeSELFIngestor.appex/Contents/MacOS/BiomeSELFIngestor""",
r"""/System/Library/PrivateFrameworks/MapsSync.framework/mapssyncd""",
r"""/System/Library/PrivateFrameworks/SiriTTSService.framework/sirittsd""",
r"""/usr/libexec/duetexpertd""",
r"""/System/Library/PrivateFrameworks/MobileAccessoryUpdater.framework/Support/fudHelperAgent""",
r"""/usr/libexec/mlhostd""",
r"""/System/Library/PrivateFrameworks/PassKitCore.framework/passd""",
r"""/System/Library/PrivateFrameworks/CommerceKit.framework/Versions/A/Resources/commerce""",
r"""/System/Library/CoreServices/Dock.app/Contents/MacOS/Dock""",
r"""/System/Library/CoreServices/SystemUIServer.app/Contents/MacOS/SystemUIServer""",
r"""/System/Library/CoreServices/Finder.app/Contents/MacOS/Finder""",
r"""/System/Library/CoreServices/Spotlight.app/Contents/MacOS/Spotlight""",
r"""/System/Library/Frameworks/QuickLookUI.framework/Versions/A/XPCServices/QuickLookUIService.xpc/Contents/MacOS/QuickLookUIService""",
r"""automountd""",
r"""/System/Library/PrivateFrameworks/AMPDevices.framework/Versions/A/Support/AMPDeviceDiscoveryAgent --launchd""",
r"""/System/Library/Frameworks/ApplicationServices.framework/Frameworks/ATS.framework/Support/fontd""",
r"""/System/Library/CoreServices/Dock.app/Contents/XPCServices/com.apple.dock.extra.xpc/Contents/MacOS/com.apple.dock.extra""",
r"""/System/Library/PrivateFrameworks/HearingCore.framework/heard""",
r"""/System/Library/Frameworks/InputMethodKit.framework/Resources/imklaunchagent""",
r"""/System/Library/Image Capture/Support/icdd""",
r"""/System/Library/PrivateFrameworks/AskPermission.framework/Versions/A/Resources/askpermissiond""",
r"""/System/Library/CoreServices/AirPlayUIAgent.app/Contents/MacOS/AirPlayUIAgent --launchd""",
r"""/System/Library/CoreServices/TextInputMenuAgent.app/Contents/MacOS/TextInputMenuAgent""",
r"""/System/Library/PrivateFrameworks/CallHistory.framework/Support/CallHistoryPluginHelper""",
r"""/System/Library/CoreServices/TextInputSwitcher.app/Contents/MacOS/TextInputSwitcher""",
r"""/Library/Apple/System/Library/PrivateFrameworks/DeviceInterface.framework/Support/deviceinterfaced""",
r"""/usr/libexec/kernelmanager_helper""",
r"""/System/Library/Frameworks/Contacts.framework/Support/contactsd""",
r"""/Library/Apple/System/Library/CoreServices/XProtect.app/Contents/XPCServices/XProtectPluginService.xpc/Contents/MacOS/XProtectPluginService""",
r"""/System/Library/PrivateFrameworks/StocksKit.framework/XPCServices/StocksKitService.xpc/Contents/MacOS/StocksKitService""",
r"""/System/Library/CoreServices/ReportSystemMemory""",
r"""/System/Library/PrivateFrameworks/SoftwareUpdate.framework/Resources/SoftwareUpdateNotificationManager.app/Contents/MacOS/SoftwareUpdateNotificationManager""",
r"""/usr/libexec/betaenrollmentagent""",
r"""/System/Library/PrivateFrameworks/TextInputUIMacHelper.framework/Versions/A/XPCServices/CursorUIViewService.xpc/Contents/MacOS/CursorUIViewService""",
r"""/System/Library/PrivateFrameworks/KerberosHelper/Helpers/DiskUnmountWatcher""",
r"""/System/Library/PrivateFrameworks/CoreSuggestions.framework/Versions/A/Support/suggestd""",
r"""/System/Library/Services/AppleSpell.service/Contents/MacOS/AppleSpell""",
r"""/usr/libexec/naturallanguaged""",
r"""/usr/libexec/keyboardservicesd""",
r"""/usr/libexec/inputanalyticsd""",
r"""/System/Library/Frameworks/ColorSync.framework/Support/colorsync.useragent""",
r"""/System/Library/Frameworks/ColorSync.framework/Versions/A/XPCServices/com.apple.ColorSyncXPCAgent.xpc/Contents/MacOS/com.apple.ColorSyncXPCAgent""",
r"""/usr/libexec/adprivacyd""",
r"""/usr/libexec/metrickitd""",
r"""/System/Library/PrivateFrameworks/PerfPowerServicesReader.framework/Versions/A/XPCServices/PerfPowerTelemetryReaderService.xpc/Contents/MacOS/PerfPowerTelemetryReaderService""",
r"""/System/Library/Frameworks/ExtensionFoundation.framework/Versions/A/XPCServices/extensionkitservice.xpc/Contents/MacOS/extensionkitservice""",
r"""/System/Library/PrivateFrameworks/BookKit.framework/Versions/A/XPCServices/com.apple.BKAgentService.xpc/Contents/MacOS/com.apple.BKAgentService""",
r"""/System/Library/PrivateFrameworks/CloudPhotoServices.framework/Versions/A/XPCServices/com.apple.CloudPhotosConfiguration.xpc/Contents/MacOS/com.apple.CloudPhotosConfiguration""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/System/Cryptexes/App/usr/libexec/com.apple.Safari.History""",
r"""/System/Cryptexes/App/usr/libexec/SafariNotificationAgent""",
r"""/System/Library/PrivateFrameworks/WebPrivacy.framework/webprivacyd""",
r"""/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/CVMServer""",
r"""/System/Library/Frameworks/MediaAccessibility.framework/Versions/A/XPCServices/com.apple.accessibility.mediaaccessibilityd.xpc/Contents/MacOS/com.apple.accessibility.mediaaccessibilityd""",
r"""/System/Cryptexes/App/System/Library/CoreServices/SafariSupport.bundle/Contents/MacOS/SafariBookmarksSyncAgent""",
r"""/System/Library/PrivateFrameworks/Synapse.framework/Support/contentlinkingd""",
r"""/System/Library/Frameworks/Translation.framework/translationd""",
r"""/System/Cryptexes/App/usr/libexec/PasswordBreachAgent""",
r"""/System/Cryptexes/App/usr/libexec/SafariLaunchAgent""",
r"""/System/Library/PrivateFrameworks/SafariSafeBrowsing.framework/com.apple.Safari.SafeBrowsing.Service""",
r"""/System/Library/PrivateFrameworks/AppPredictionFoundation.framework/Versions/A/XPCServices/AppPredictionIntentsHelperService.xpc/Contents/MacOS/AppPredictionIntentsHelperService""",
r"""/System/Library/Frameworks/NetFS.framework/Versions/A/XPCServices/PlugInLibraryService.xpc/Contents/MacOS/PlugInLibraryService""",
r"""/System/iOSSupport/System/Library/PrivateFrameworks/HomeEnergyDaemon.framework/Support/homeenergyd""",
r"""/System/Library/PrivateFrameworks/MediaAnalysisAccess.framework/Versions/A/XPCServices/mediaanalysisd-access.xpc/Contents/MacOS/mediaanalysisd-access""",
r"""/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/intelligenceplatformd""",
r"""/usr/libexec/backgroundassets.user""",
r"""/Library/Apple/System/Library/CoreServices/XProtect.app/Contents/MacOS/XProtect""",
r"""/Library/Apple/System/Library/CoreServices/XProtect.app/Contents/MacOS/XProtect""",
r"""cloudphotod""",
r"""/usr/libexec/dprivacyd""",
r"""/System/Library/PrivateFrameworks/GeoAnalytics.framework/geoanalyticsd""",
r"""/usr/libexec/feedbackd""",
r"""/usr/libexec/proactiveeventtrackerd""",
r"""/usr/libexec/dprivacyd""",
r"""/System/Library/PrivateFrameworks/AppleNeuralEngine.framework/XPCServices/ANEStorageMaintainer.xpc/Contents/MacOS/ANEStorageMaintainer""",
r"""/System/Library/PrivateFrameworks/AppleNeuralEngine.framework/XPCServices/ANEStorageMaintainer.xpc/Contents/MacOS/ANEStorageMaintainer""",
r"""/usr/sbin/distnoted agent""",
r"""/System/Library/PrivateFrameworks/AssistantServices.framework/Versions/A/XPCServices/media-indexer.xpc/Contents/MacOS/media-indexer""",
r"""/System/Library/PrivateFrameworks/OnDeviceStorage.framework/Support/amsondevicestoraged""",
r"""/System/Library/PrivateFrameworks/AMPLibrary.framework/Versions/A/Support/AMPLibraryAgent --launchd""",
r"""/System/Library/PrivateFrameworks/PodcastServices.framework/XPCServices/PodcastContentService.xpc/Contents/MacOS/PodcastContentService""",
r"""/System/Library/PrivateFrameworks/AMPLibrary.framework/Versions/A/Support/AMPArtworkAgent --launchd""",
r"""/System/Library/PrivateFrameworks/IMDPersistence.framework/IMAutomaticHistoryDeletionAgent.app/Contents/MacOS/IMAutomaticHistoryDeletionAgent""",
r"""/usr/libexec/tipsd""",
r"""/System/Library/PrivateFrameworks/RemoteManagement.framework/RemoteManagementAgent""",
r"""/System/Library/PrivateFrameworks/SafariFoundation.framework/Versions/A/XPCServices/SafariConfigurationSubscriber.xpc/Contents/MacOS/SafariConfigurationSubscriber""",
r"""/System/Library/PrivateFrameworks/RemoteManagement.framework/XPCServices/SecuritySubscriber.xpc/Contents/MacOS/SecuritySubscriber""",
r"""/System/Library/PrivateFrameworks/RemoteManagement.framework/XPCServices/InteractiveLegacyProfilesSubscriber.xpc/Contents/MacOS/InteractiveLegacyProfilesSubscriber""",
r"""/System/Library/PrivateFrameworks/RemoteManagement.framework/XPCServices/ScreenSharingSubscriber.xpc/Contents/MacOS/ScreenSharingSubscriber""",
r"""/System/Library/PrivateFrameworks/RemoteManagement.framework/XPCServices/LegacyProfilesSubscriber.xpc/Contents/MacOS/LegacyProfilesSubscriber""",
r"""/System/Library/PrivateFrameworks/RemoteManagement.framework/XPCServices/PasscodeSettingsSubscriber.xpc/Contents/MacOS/PasscodeSettingsSubscriber""",
r"""/System/Library/PrivateFrameworks/RemoteManagement.framework/XPCServices/AccountSubscriber.xpc/Contents/MacOS/AccountSubscriber""",
r"""/System/Library/PrivateFrameworks/RemoteManagement.framework/XPCServices/ManagementTestSubscriber.xpc/Contents/MacOS/ManagementTestSubscriber""",
r"""/System/Library/PrivateFrameworks/RemoteManagement.framework/XPCServices/ASConfigurationSubscriber.xpc/Contents/MacOS/ASConfigurationSubscriber""",
r"""/System/Library/PrivateFrameworks/RemoteManagement.framework/XPCServices/ManagedSettingsSubscriber.xpc/Contents/MacOS/ManagedSettingsSubscriber""",
r"""/usr/libexec/sysdiagnosed""",
r"""/System/Library/Frameworks/NetFS.framework/Versions/A/XPCServices/PlugInLibraryService.xpc/Contents/MacOS/PlugInLibraryService""",
r"""/System/Cryptexes/App/usr/libexec/AuthenticationServicesAgent""",
r"""/System/Library/CoreServices/EscrowSecurityAlert.app/Contents/MacOS/EscrowSecurityAlert""",
r"""/usr/libexec/seserviced""",
r"""/System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/Support/akd""",
r"""/usr/sbin/cfprefsd agent""",
r"""/usr/sbin/cfprefsd agent""",
r"""/usr/sbin/cfprefsd agent""",
r"""/usr/sbin/cfprefsd agent""",
r"""/usr/sbin/cfprefsd agent""",
r"""/usr/libexec/ciphermld""",
r"""/System/Library/PrivateFrameworks/BusinessChatService.framework/businessservicesd""",
r"""/System/Library/PrivateFrameworks/MessagesBlastDoorSupport.framework/Versions/A/XPCServices/MessagesBlastDoorService.xpc/Contents/MacOS/MessagesBlastDoorService""",
r"""/System/Library/PrivateFrameworks/Categories.framework/Versions/A/XPCServices/CategoriesService.xpc/Contents/MacOS/CategoriesService""",
r"""/System/Library/PrivateFrameworks/ContextKit.framework/Versions/A/XPCServices/ContextService.xpc/Contents/MacOS/ContextService""",
r"""/usr/libexec/microstackshot""",
r"""/System/Library/PrivateFrameworks/EcosystemAnalytics.framework/Support/ecosystemanalyticsd""",
r"""/System/Library/PrivateFrameworks/Noticeboard.framework/Versions/A/Resources/nbagent.app/Contents/MacOS/nbagent""",
r"""/System/Library/PrivateFrameworks/AvatarPersistence.framework/Support/avatarsd""",
r"""/System/Library/CoreServices/PowerChime.app/Contents/MacOS/PowerChime""",
r"""/System/Library/PrivateFrameworks/MobileAccessoryUpdater.framework/XPCServices/EAUpdaterService.xpc/Contents/MacOS/EAUpdaterService""",
r"""/System/Library/CoreServices/OSDUIHelper.app/Contents/MacOS/OSDUIHelper""",
r"""/usr/libexec/wifivelocityd""",
r"""/System/Library/PrivateFrameworks/AppSSO.framework/Support/AppSSOAgent.app/Contents/MacOS/AppSSOAgent""",
r"""/usr/libexec/captiveagent""",
r"""/System/Library/PrivateFrameworks/AssetCacheServices.framework/Versions/A/XPCServices/AssetCacheLocatorService.xpc/Contents/MacOS/AssetCacheLocatorService -d""",
r"""/System/Library/PrivateFrameworks/NewsDaemon.framework/newsd""",
r"""/System/Library/PrivateFrameworks/StreamingExtractor.framework/Versions/A/XPCServices/STExtractionService.privileged.xpc/Contents/MacOS/STExtractionService.privileged""",
r"""/System/Library/PrivateFrameworks/MobileAsset.framework/Versions/A/XPCServices/ManifestStorageService.xpc/Contents/MacOS/ManifestStorageService""",
r"""/System/Library/PrivateFrameworks/AssetCacheServices.framework/Versions/A/XPCServices/AssetCacheLocatorService.xpc/Contents/MacOS/AssetCacheLocatorService -a""",
r"""/System/Library/PrivateFrameworks/StreamingZip.framework/Versions/A/XPCServices/com.apple.StreamingUnzipService.privileged.xpc/Contents/MacOS/com.apple.StreamingUnzipService.privileged""",
r"""/System/Library/PrivateFrameworks/CoreSuggestions.framework/Versions/A/Support/reversetemplated""",
r"""/usr/libexec/trustd --agent""",
r"""/usr/libexec/swtransparencyd""",
r"""/System/Library/PrivateFrameworks/CloudTelemetry.framework/Versions/A/XPCServices/CloudTelemetryService.xpc/Contents/MacOS/CloudTelemetryService""",
r"""/System/Library/Frameworks/CoreSpotlight.framework/spotlightknowledged -x""",
r"""/System/Library/PrivateFrameworks/AppleNeuralEngine.framework/XPCServices/ANECompilerService.xpc/Contents/MacOS/ANECompilerService""",
r"""/System/Library/PrivateFrameworks/Install.framework/Frameworks/DistributionKit.framework/Versions/A/XPCServices/DistributionHelper.xpc/Contents/MacOS/DistributionHelper""",
r"""/usr/libexec/trustd""",
r"""/System/Library/PrivateFrameworks/WeatherDaemon.framework/weatherd""",
r"""/System/Library/PrivateFrameworks/ProtectedCloudStorage.framework/Helpers/ProtectedCloudKeySyncing""",
r"""/System/Library/PrivateFrameworks/DeviceCheckInternal.framework/devicecheckd""",
r"""/usr/libexec/tzd""",
r"""/System/Library/PrivateFrameworks/XprotectFramework.framework/Versions/A/XPCServices/XProtectUpdateService.xpc/Contents/MacOS/XProtectUpdateService""",
r"""/usr/libexec/tznotify""",
r"""/usr/libexec/studentd""",
r"""/System/Library/PrivateFrameworks/AmbientDisplay.framework/Versions/A/XPCServices/com.apple.AmbientDisplayAgent.xpc/Contents/MacOS/com.apple.AmbientDisplayAgent""",
r"""/System/Library/Frameworks/ColorSync.framework/Versions/A/XPCServices/com.apple.ColorSyncXPCAgent.xpc/Contents/MacOS/com.apple.ColorSyncXPCAgent""",
r"""/System/Library/PrivateFrameworks/CoreLSKD.framework/Versions/A/lskdd""",
r"""/System/Library/PrivateFrameworks/IntelligencePlatformCompute.framework/Versions/A/XPCServices/IntelligencePlatformComputeService.xpc/Contents/MacOS/IntelligencePlatformComputeService""",
r"""/usr/libexec/trustd --agent""",
r"""/System/Library/Frameworks/Speech.framework/Versions/A/XPCServices/localspeechrecognition.xpc/Contents/MacOS/localspeechrecognition""",
r"""/System/Library/Frameworks/ApplicationServices.framework/Frameworks/PrintCore.framework/Versions/A/printtool""",
r"""/System/Library/PrivateFrameworks/CommunicationsFilter.framework/CMFSyncAgent""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/usr/libexec/PerfPowerServices""",
r"""/System/Library/PrivateFrameworks/CoreEmbeddedSpeechRecognition.framework/Versions/A/XPCServices/com.apple.siri.embeddedspeech.xpc/Contents/MacOS/com.apple.siri.embeddedspeech""",
r"""/System/Applications/News.app/Contents/PlugIns/NewsToday2.appex/Contents/MacOS/NewsToday2""",
r"""/System/Applications/Weather.app/Contents/PlugIns/WeatherWidget.appex/Contents/MacOS/WeatherWidget""",
r"""/usr/sbin/netbiosd""",
r"""/usr/libexec/trustd --agent""",
r"""/usr/libexec/trustd --agent""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker_shared -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared""",
r"""/usr/libexec/biomesyncd""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker_shared -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker_shared -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker_shared -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker_shared -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker_shared -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared""",
r"""/System/Library/Frameworks/CoreServices.framework/Frameworks/Metadata.framework/Versions/A/Support/mdworker_shared -s mdworker -c MDSImporterWorker -m com.apple.mdworker.shared""",
r"""/System/Library/Frameworks/ExtensionFoundation.framework/Versions/A/XPCServices/extensionkitservice.xpc/Contents/MacOS/extensionkitservice""",
r"""/System/Library/ExtensionKit/Extensions/PackageThumbnailExtension.appex/Contents/MacOS/PackageThumbnailExtension""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/System/Library/Frameworks/Metal.framework/Versions/A/XPCServices/MTLCompilerService.xpc/Contents/MacOS/MTLCompilerService""",
r"""/usr/libexec/remoted""",
r"""login -pf tal""",
r"""-zsh""",
r"""sudo -i""",
r"""-sh""",
r"""ps -A""",
r"""pbcopy""",
})